configured_endpoints: 44
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-real-deal%2Fthe-real-deal-536762657d8e1e5eda65b71848ccff0d9f75716b50d20c03361bd438e8e681c3.yml
